apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:

      - name: backend

        image: bilal22992/backend:latest

        ports:
        - containerPort: 5001

        env:

        - name: API_KEY
          valueFrom:
           secretKeyRef:
             name: backend-secret
             key: API_KEY
